openapi: 3.0.3
info:
  title: User Registration API
  version: 1.0.0
  x-api-name: Users

paths:
  /users:
    post:
      tags:
        - UserDetails
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegistrationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UserRegistrationRequest:
      type: object
      required:
        - name
        - email
        - password
        - phones
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/ContactPhone'

    ContactPhone:
      type: object
      required:
        - number
        - citycode
        - countrycode
      properties:
        number:
          type: string
        citycode:
          type: string
        countrycode:
          type: string

    UserRegistrationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
        email:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/ContactPhone'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
        token:
          type: string
        isactive:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        mensaje:
          type: string